export const dummyPlayers = [
  {
    id: 1,
    name: "박도윤",
    position: "스트라이커",
    subPosition: "윙포워드",
    note: "공간 침투와 마무리에 강한 전형적인 스트라이커",
    image: "https://picsum.photos/id/1011/300/200",
    achievements: [
      { tournament: "감드컵 시즌1", result: "우승" },
      { tournament: "감드컵 시즌2", result: "준우승" },
    ],
  },
  {
    id: 2,
    name: "이하준",
    position: "골키퍼",
    subPosition: "수비수",
    note: "순간 반사 능력 뛰어난 안정적인 키퍼",
    image: "https://picsum.photos/id/1027/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "준우승" }],
  },
  {
    id: 3,
    name: "김서연",
    position: "센터 미드필더",
    subPosition: "수비형 미드필더",
    note: "중앙 장악력과 패싱 능력이 뛰어난 중심축",
    image: "https://picsum.photos/id/1044/300/200",
    achievements: [
      { tournament: "감드컵 시즌2", result: "우승" },
      { tournament: "감드컵 시즌2", result: "MVP 수상" },
    ],
  },
  {
    id: 4,
    name: "정하린",
    position: "수비수",
    subPosition: "풀백",
    note: "1:1 수비와 태클에 능한 안정적인 수비수",
    image: "https://picsum.photos/id/1005/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "수비왕" }],
  },
  {
    id: 5,
    name: "최지호",
    position: "윙포워드",
    subPosition: "스트라이커",
    note: "스피드와 돌파력이 뛰어난 공격 자원",
    image: "https://picsum.photos/id/1033/300/200",
    achievements: [
      { tournament: "감드컵 시즌3", result: "득점왕" },
      { tournament: "감드컵 시즌3", result: "우승" },
    ],
  },
  {
    id: 6,
    name: "윤시우",
    position: "풀백",
    subPosition: "수비수",
    note: "활동량과 투지가 뛰어난 측면 수비 자원",
    image: "https://picsum.photos/id/1060/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "베스트11" }],
  },
  {
    id: 7,
    name: "배서준",
    position: "수비형 미드필더",
    subPosition: "센터 미드필더",
    note: "태클과 중거리 슛 모두 갖춘 다재다능한 미드필더",
    image: "https://picsum.photos/id/1074/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "태클왕" }],
  },
  {
    id: 8,
    name: "장예린",
    position: "올라운더",
    subPosition: "센터 미드필더",
    note: "필요한 곳에 항상 있는 전천후 플레이어",
    image: "https://picsum.photos/id/1084/300/200",
    achievements: [{ tournament: "감드컵 시즌3", result: "멀티포지션상" }],
  },
  {
    id: 9,
    name: "서하윤",
    position: "수비형 미드필더",
    subPosition: "풀백",
    note: "수비 밸런스 조율에 능하며 침착한 경기 운영",
    image: "https://picsum.photos/id/1018/300/200",
    achievements: [
      { tournament: "감드컵 시즌3", result: "준우승" },
      { tournament: "감드컵 시즌3", result: "베스트11" },
    ],
  },
  {
    id: 10,
    name: "강민재",
    position: "올라운더",
    subPosition: "윙포워드",
    note: "공격-수비 모두 소화 가능한 에너자이저",
    image: "https://picsum.photos/id/1003/300/200",
    achievements: [
      { tournament: "감드컵 시즌2", result: "전 경기 풀타임" },
      { tournament: "감드컵 시즌2", result: "도움왕" },
    ],
  },
  {
    id: 11,
    name: "선수11",
    position: "풀백",
    subPosition: "윙포워드",
    note: "날카로운 패싱과 경기 조율 능력 보유",
    image: "https://picsum.photos/id/1011/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "MVP 수상" }],
  },
  {
    id: 12,
    name: "선수12",
    position: "스트라이커",
    subPosition: "윙포워드",
    note: "날카로운 패싱과 경기 조율 능력 보유",
    image: "https://picsum.photos/id/1012/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "득점왕" }],
  },
  {
    id: 13,
    name: "선수13",
    position: "윙포워드",
    subPosition: "센터 미드필더",
    note: "날카로운 패싱과 경기 조율 능력 보유",
    image: "https://picsum.photos/id/1013/300/200",
    achievements: [{ tournament: "감드컵 시즌3", result: "우승" }],
  },
  {
    id: 14,
    name: "선수14",
    position: "스트라이커",
    subPosition: "풀백",
    note: "강한 체력과 넓은 활동 범위",
    image: "https://picsum.photos/id/1014/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "준우승" }],
  },
  {
    id: 15,
    name: "선수15",
    position: "스트라이커",
    subPosition: "윙포워드",
    note: "강한 체력과 넓은 활동 범위",
    image: "https://picsum.photos/id/1015/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "우승" }],
  },
  {
    id: 16,
    name: "선수16",
    position: "센터 미드필더",
    subPosition: "풀백",
    note: "강한 체력과 넓은 활동 범위",
    image: "https://picsum.photos/id/1016/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "MVP 수상" }],
  },
  {
    id: 17,
    name: "선수17",
    position: "풀백",
    subPosition: "윙포워드",
    note: "강한 체력과 넓은 활동 범위",
    image: "https://picsum.photos/id/1017/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "준우승" }],
  },
  {
    id: 18,
    name: "선수18",
    position: "수비형 미드필더",
    subPosition: "풀백",
    note: "날카로운 패싱과 경기 조율 능력 보유",
    image: "https://picsum.photos/id/1018/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "준우승" }],
  },
  {
    id: 19,
    name: "선수19",
    position: "풀백",
    subPosition: "수비수",
    note: "날카로운 패싱과 경기 조율 능력 보유",
    image: "https://picsum.photos/id/1019/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "수비왕" }],
  },
  {
    id: 20,
    name: "선수20",
    position: "수비형 미드필더",
    subPosition: "윙포워드",
    note: "슈팅 정확도가 뛰어난 해결사",
    image: "https://picsum.photos/id/1020/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "베스트11" }],
  },
  {
    id: 21,
    name: "선수21",
    position: "올라운더",
    subPosition: "센터 미드필더",
    note: "끈질긴 수비력으로 상대 공격을 봉쇄",
    image: "https://picsum.photos/id/1021/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "베스트11" }],
  },
  {
    id: 22,
    name: "선수22",
    position: "골키퍼",
    subPosition: "풀백",
    note: "강한 체력과 넓은 활동 범위",
    image: "https://picsum.photos/id/1022/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "득점왕" }],
  },
  {
    id: 23,
    name: "선수23",
    position: "수비형 미드필더",
    subPosition: "윙포워드",
    note: "강한 체력과 넓은 활동 범위",
    image: "https://picsum.photos/id/1023/300/200",
    achievements: [{ tournament: "감드컵 시즌1", result: "MVP 수상" }],
  },
  {
    id: 24,
    name: "선수24",
    position: "풀백",
    subPosition: "수비수",
    note: "슈팅 정확도가 뛰어난 해결사",
    image: "https://picsum.photos/id/1024/300/200",
    achievements: [{ tournament: "감드컵 시즌3", result: "MVP 수상" }],
  },
  {
    id: 25,
    name: "선수25",
    position: "올라운더",
    subPosition: "풀백",
    note: "슈팅 정확도가 뛰어난 해결사",
    image: "https://picsum.photos/id/1025/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "수비왕" }],
  },
  {
    id: 26,
    name: "선수26",
    position: "수비수",
    subPosition: "센터 미드필더",
    note: "슈팅 정확도가 뛰어난 해결사",
    image: "https://picsum.photos/id/1026/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "준우승" }],
  },
  {
    id: 27,
    name: "선수27",
    position: "윙포워드",
    subPosition: "센터 미드필더",
    note: "끈질긴 수비력으로 상대 공격을 봉쇄",
    image: "https://picsum.photos/id/1027/300/200",
    achievements: [{ tournament: "감드컵 시즌3", result: "수비왕" }],
  },
  {
    id: 28,
    name: "선수28",
    position: "스트라이커",
    subPosition: "센터 미드필더",
    note: "슈팅 정확도가 뛰어난 해결사",
    image: "https://picsum.photos/id/1028/300/200",
    achievements: [{ tournament: "감드컵 시즌3", result: "도움왕" }],
  },
  {
    id: 29,
    name: "선수29",
    position: "올라운더",
    subPosition: "윙포워드",
    note: "강한 체력과 넓은 활동 범위",
    image: "https://picsum.photos/id/1029/300/200",
    achievements: [{ tournament: "감드컵 시즌2", result: "MVP 수상" }],
  },
  {
    id: 30,
    name: "선수30",
    position: "골키퍼",
    subPosition: "윙포워드",
    note: "슈팅 정확도가 뛰어난 해결사",
    image: "https://picsum.photos/id/1030/300/200",
    achievements: [{ tournament: "감드컵 시즌3", result: "수비왕" }],
  },
];

export const positionMenu = [
  "포지션 선택",
  "스트라이커",
  "윙포워드",
  "센터 미드필더",
  "수비형 미드필더",
  "수비수",
  "풀백",
  "골키퍼",
  "올라운더",
];

export const softColors = [
  "#FF6B6B", // 레드
  "#FFB100", // 오렌지
  "#4ECDC4", // 청록
  "#1A73E8", // 구글블루
  "#36A2EB", // 밝은 파랑
  "#7C3AED", // 보라
  "#10B981", // 에메랄드
  "#F59E0B", // 머스타드
  "#E11D48", // 다홍
  "#3B82F6", // 중간 파랑
];
