import type { Metadata } from "next";
import "./globals.css";
import ModeBtn from "@/_components/common/ModeBtn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        <footer></footer>
        <ModeBtn />
      </body>
    </html>
  );
}
