import type { Metadata } from "next";
import "./globals.css";
import ModeBtn from "@/_components/common/ModeBtn";
import MenuBtn from "@/_components/common/MenuBtn";
import { AlertProvider } from "@/_context/AlertContext";
import SessionProviderWrapper from "./SessionProviderWrapper";
import AdminBadge from "@/_components/common/AdminBadge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <AlertProvider>
            <main>{children}</main>
            <footer></footer>
            <MenuBtn />
            <ModeBtn />
            <AdminBadge />
          </AlertProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
